### PR TITLE
fix: launchpad streaming not working.

### LINKED ISSUE #549: Launchpad streaming not working
Opening a new stream to the launchpad doesn't work. The button spins and hangs. I captured the screenshot.
Screen Shot 2022-03-03 at 9 29 06 AM

### PR DESCRIPTION
**Pull request by zhyd1997**
Fixes #549

### CODE REVIEW

**Comment by zhyd1997** [comment]
This is a draft PR because there're still some issues called `superFluid.host.batchCall()`.

but there is no hanging out when clicked start button.

**Comment by zhyd1997** [comment]
If you encounter error like so:

gas fee too low error

**Try to increment the gas fee**.

**Comment by mikeghen** [comment]
@zhyd1997 thanks for doing this, is this going to put some feedback for the user when they get the "txn underpriced" error?

**Comment by mikeghen** [comment]
NVM my comment

**Review by mikeghen — APPROVED** [review]

**Pull request merged**
