### PR TITLE
add test.yml

### LINKED ISSUE #504: Add test GitHub workflow
Currently, we are testing our codebase only on PRs, It would be great if we test our codebase after merging to the main branch

- We can know any regression issues occur
- Test may pass in PR if the branch is not rebased but fail in the main branch

### PR DESCRIPTION
**Pull request by geekypandey**
Github Action to run test on pull request and also on merging to main or
v2 branch

Fixes #504

**Changes proposed in this pull request:**

- add github actions to run test when pull request is created and also when it is merged into main or v2 branch

### CODE REVIEW

**Comment by mikeghen** [comment]
@geekypandey, I didn't realize we had tests 😅 so this just runs the tests as a github action? Itll be one of the checks right?

**Comment by geekypandey** [comment]
yes, so currently there is just one test file containing five test [here](https://github.com/Ricochet-Exchange/ricochet-frontend/blob/v2/src/utils/__tests__/balances.test.ts). But if more tests are added, this GitHub action will run all of them.

**Comment by 0xSero** [comment]
Progress on this?

**Comment by geekypandey** [comment]
I guess this PR is okay. It runs the tests as a Github Action as required. @mikeghen waiting for your approval.

**Comment by mikeghen** [comment]
I merged this because I think the GitHub actions stuff is pretty non-invasive, I'm not familiar with the test suite we have in the app so we'll have to see how this goes, make create a lot of failing checks

**Comment by geekypandey** [comment]
yeah. Also, one thought that we can put this testing ci in the [build pipeline](https://github.com/Ricochet-Exchange/ricochet-frontend/blob/v2/.github/workflows/create-update-pr-env.yml) , so that the application gets build only when the tests are passing.

**Pull request merged**
