### PR TITLE
Stream animated numbers

### LINKED ISSUE #777: Animate incoming/outgoing flowrate
## Issue: 

Our frontend could use some basic animation to improve UX, by animating the flow from one token into another we can provide users a more visually appealing and less complex application.

### How to solve this:

 - find the per second flowrate for each stream
 - create a function which updates the flowrate on frontend on a second per second basis by incrementing the total streamed so far by the flow rate per second.
  - ensure this function doesn't make additional calls to the backend, all this can be done in the TS
  
### Great example:

You can effectively solve this bounty by backwards engineering the below example and implementing it in Ricochet-frontend:

### PR DESCRIPTION
**Pull request by rakhi2104**
Fixes #777 

**Changes proposed in this pull request:**

- Introduce Animated amount component 
- Calculate incoming and outgoing flow rates and animate accordingly

https://user-images.githubusercontent.com/17671710/190930710-bac8015b-018d-477b-a985-a744ebb84e64.mp4

### CODE REVIEW

**Review by mikeghen — CHANGES_REQUESTED** [review]
Im not sure whats going wrong but the ibAlluoUSD balances are completely different in 3 different places, the values should be the same

Screen Shot 2022-09-23 at 12 46 24 PM

**Review by mikeghen — CHANGES_REQUESTED** [review]
Can you make sure these balances can't show as negative? I defintely think the "streamed so far" amount is being deducted from the balances when the animation is happening.

Screen Shot 2022-09-23 at 12 49 29 PM

**Review by mikeghen — CHANGES_REQUESTED** [review]
If USDCx is animated in one market, can you make it animated in all the markets? I dont have USDC>ETH or USDC>RIC so the USDCx balance isn't animated, but it should be animated since the USDCx balance is being reduced by streaming.

Sep-23-2022 12-50-55

**Review by mikeghen — COMMENTED** [review]
- [ ] the USDCx balance isn't animated
- [ ] ibAlluoUSD is counting upwards but is should be counting down since there's to streams ibAlluoUSD > ibAlluoETH/BTC

Sep-23-2022 12-54-20

**Review by mikeghen — CHANGES_REQUESTED** [review]
There aren't any animations on the wallet page anymore

**Comment by 0xSero** [comment]
This PR will be closed, unfortunately, the page is not consistently behaving as described in scope of bounty.

We can re-open if the issues mentioned by @mikeghen are resolved,

**Pull request closed without merging**
