### PR TITLE
Bug/fix affiliate

### PR DESCRIPTION
**Pull request by seemwavy**
Fixes #

**Changes proposed in this pull request:**

-Fix referral name, fixed referral ID clause, clear whitespace
-Fix branch name
-

### CODE REVIEW

**Review by mikeghen — APPROVED** [review]
LGTM, @Seroxdesign you can approve and merge as you see fit 👍

**Comment by 0xSero** [comment]
@seemwavy 

Changes requested in this PR haven't been made:
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/860

**Review by 0xSero — CHANGES_REQUESTED** [review]
This can be improved as follows:

```
  useEffect(() => {
    if (!contract) {
      setCurrentReferralId(address.toLowerCase().slice(0, 10));
      return;
    } 
    const setReferralId = async () => {
      let currentReferralId = await contract.methods.addressToAffiliate(address.toLowerCase()).call();
      if (currentReferralId !== '0') {
        currentReferralId = await contract.methods.affiliates(currentReferralId).call();
        setCurrentReferralId(currentReferralId.name);
        return;
      }
    }
    setReferralId();
  }, [address, contract]);
```

## What's different:

### Add new param to useEffect hook:

A new parameter was added to the useEffect dependency array, the new param is contract.

The way useEffect works, is it runs on the first page render **always**, then it runs again whenever one of the dependencies: **(in this example it's address and contract)** are updated.   

We added **contract** to ensure that the function will run whenever the contract is initialized. Sometimes it could be after the useEffect runs.

For more on this: [A guide on React's useEffect hook](https://www.w3schools.com/react/react_useeffect.asp)

---------------------------------------

### Remove async function calls from if statement:

A common practice in React useEffect hooks is to avoid nested if statements by inverting if statement:

Example: 

Instead of: 
```
if (some condition)
  {
    Some code...            
 }
```

We can do the following: 
```
  if (!some condition) return;
   Some code...
```

This reduces complexity, in the if (!contract) { do something; return } block we handled the case where no contract is available, the function will return and the useEffect will have run it's course. if the contract is available we skip over that code and call our async function.

To learn more about this: [Invert if statement to reduce nesting](https://stackoverflow.com/questions/268132/invert-if-statement-to-reduce-nesting)
----------------------------------------------

If you can make the following improvements, and test to ensure it is working as expected I will merge this in ASAP.

**Comment by 0xSero** [comment]
image

Good job! it's working

**Review by 0xSero — APPROVED** [review]

**Pull request merged**
