### PR TITLE
PR for a subtask of List REXTwoWayMarket

### PR DESCRIPTION
**Pull request by josealonso**
PR for a small part of #298. It contains some errors, It has to reviewed by @vaibhavgeek.

### CODE REVIEW

**Comment by josealonso** [comment]
Only look at the changes in `ethereum.ts`

**Comment by samirsalem** [comment]
Looks like the CI of this has failed because yarn build failed ( maybe some syntax/dependency error ) that's why the PR env creation has failed.

**Comment by josealonso** [comment]
> Looks like the CI of this has failed because yarn build failed ( maybe some syntax/dependency error ) that's why the PR env creation has failed.

As I said in a previous comment, there was a compile error. I messed up the *else* blocks in TS, so don't worry. I just wanted to show my code to @vaibhavgeek. Thanks, @samirsalem !!

**Comment by vaibhavgeek** [comment]
@josealonso Please delete this Pull request.

**Pull request closed without merging**
