### PR TITLE
Ft/distribution

### PR DESCRIPTION
**Pull request by mindsgn**
animation distribution working need to get when the next distribution will happen.

### CODE REVIEW

**Comment by mikeghen** [comment]
@mindsgn could you just show the `lastDistributionAt` value? There's no way to determine when the next dist. is, only can get when the LAST distribution happened so lets show that

**Review by mikeghen — CHANGES_REQUESTED** [review]
Lets just show last distribution date/time for each market, not this loading animation, sorry I didn't know this was something someone asked you to do I would have told you all that you cant get next distribution at values, so loading animation wont work here, just show last time distributed

**Comment by mindsgn** [comment]
@mikeghen  Okay, I will make the changes then submit another PR.

**Comment by mikeghen** [comment]
Will reopen a new PR for this since the automated environment for this isn't updating

**Pull request closed without merging**
