### PR TITLE
Bugfix: Upgrade Approval

### PR DESCRIPTION
**Pull request by jo-chemla**
Was checking allowance against balance of supertoken instead of underlying token.
Plus added function calls to sushi/wmatic

```js
  // const hasApprove = Number(amount) > Number(balances && balances[superTokenAddress]);
  const hasApprove = Number(amount) > Number(balances && balances[tokenAddress]);
```

### CODE REVIEW

**Comment by jo-chemla** [comment]
Hard to test, but it was working in every case I tried, so please do further testing as well to ensure this fixes the bug encountered by most.

**Review by mikeghen — APPROVED** [review]
Nice find @jo-chemla 🤝 💰

**Comment by abstractpoint** [comment]
I actually also started looking at it yesterday.
I think this is still broken in a different way. If user had any approved amount (allowance) before, that approved amount will always be more than the balance, because it's comparing number in WEI to number in ETH units.

I had just 1 DAI allowance approved, and it still lets me do an Upgrade transaction which of course fails.
I think users might be locked up if they do any approves that are not unlimited?

Screenshot 2021-11-17 at 06 56 26
Screenshot 2021-11-17 at 06 59 24
Screenshot 2021-11-17 at 06 59 39

**Comment by jo-chemla** [comment]
woosh you're indeed right, I can fix that in the evening!

**Pull request merged**
