### PR TITLE
Add Lighthouse CI for website benchmarking to GitHub Actions

### LINKED ISSUE #508: Add lighthouse CI
This workflow will report our website quality

https://web.dev/measure/

We will be using Google's gh image to achieve this

Screenshot 2022-02-26 at 12 12 16 PM

### PR DESCRIPTION
**Pull request by hrishibhattu**
Fixes #508 

**Changes proposed in this pull request:**

- Integrated Lighthouse CI with GitHub Actions
- Temporary Link is generated each time a pull request is created/updated and commented in the same PR thread

Tested to be working in PR: https://github.com/hrishibhattu/ricochet-frontend/pull/2#issuecomment-1053634452

Issue fixed with @geekypandey 😀

### CODE REVIEW

**Comment by hrishibhattu** [comment]
Hi @bigint , thought I'd just remind you to review this change! 😄

**Comment by mikeghen** [comment]
I would like to merge this but want to make sure there aren't going to be any CI problems when I do, @samirsalem, how do you feel about this? Looks good to you?

**Comment by shreyaspapi** [comment]
@mikeghen I don't see any other CI clashing here.

**Review by mikeghen — APPROVED** [review]

**Comment by mikeghen** [comment]
OK, I will merge this and we'll see what happens, heads up @samirsalem, hopefully this doesn't cause you any grief 😄

**Comment by mikeghen** [comment]
@hrishibhattu, this actually broke the Heroku build with error:
```
<--- Last few GCs --->
[2235:0x5e74bd0]   348590 ms: Mark-sweep 2521.8 (2600.0) -> 2518.5 (2597.8) MB, 3872.0 / 0.6 ms  (average mu = 0.102, current mu = 0.020) allocation failure scavenge might not succeed
[2235:0x5e74bd0]   351573 ms: Mark-sweep 2518.5 (2597.8) -> 2518.5 (2597.8) MB, 2982.7 / 0.1 ms  (average mu = 0.058, current mu = 0.000) allocation failure scavenge might not succeed
<--- JS stacktrace --->
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa3aaf0 node::Abort() [/tmp/build_e39a2545/.heroku/node/bin/node]
 2: 0x970199 node::FatalError(char const*, char const*) [/tmp/build_e39a2545/.heroku/node/bin/node]
 3: 0xbba45e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/tmp/build_e39a2545/.heroku/node/bin/node]
 4: 0xbba7d7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/tmp/build_e39a2545/.heroku/node/bin/node]
 5: 0xd769e5  [/tmp/build_e39a2545/.heroku/node/bin/node]
 6: 0xd7756f  [/tmp/build_e39a2545/.heroku/node/bin/node]
 7: 0xd853ab v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/tmp/build_e39a2545/.heroku/node/bin/node]
 8: 0xd87b7e v8::internal::Heap::CollectAllAvailableGarbage(v8::internal::GarbageCollectionReason) [/tmp/build_e39a2545/.heroku/node/bin/node]
 9: 0xd88fbb v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/tmp/build_e39a2545/.heroku/node/bin/node]
10: 0xd4e73d v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/tmp/build_e39a2545/.heroku/node/bin/node]
11: 0xd4a999 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [/tmp/build_e39a2545/.heroku/node/bin/node]
12: 0xd4aa54 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/tmp/build_e39a2545/.heroku/node/bin/node]
13: 0xed8efe  [/tmp/build_e39a2545/.heroku/node/bin/node]
14: 0xed904d  [/tmp/build_e39a2545/.heroku/node/bin/node]
15: 0x1077573 v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [/tmp/build_e39a2545/.heroku/node/bin/node]
16: 0x1448e19  [/tmp/build_e39a2545/.heroku/node/bin/node]
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
-----> Timed out running buildpack React.js (create-react-app) multi
 !     Push failed
 ```
 Not sure if the resolution is to just add resources on heroku, have a look and let me know what you think about it

**Comment by hrishibhattu** [comment]
Hi @mikeghen , I just made a new PR #568 which passed all the checks.

I looked through my commits, and can't find any reason that this Lighthouse CI action which is entirely run on Github actions, on Github's servers, should interfere with further Heroku deployment, from what I can tell.
Can you please provide more context/how the Heroku build is done?

And yes, judging by the stack trace, it seems like the node environment option ```NODE_OPTIONS: --max-old-space-size=8192``` to increase memory might be the solution for the Heroku deployment.

Thanks!

**Pull request merged**
