### PR TITLE
chore: remove unused dependencies

### LINKED ISSUE #450: Remove unused dependencies
This will reduce our app bundle size

### PR DESCRIPTION
**Pull request by bigint**
Fixes #450

### CODE REVIEW

**Comment by bigint** [comment]
cc @samirsalem can you review this? 🙏🏻

**Review by Seroxdesign — CHANGES_REQUESTED** [review]
I've went over these changes and I see that there is a conflict that must be resolved before I can approve the PR

**Comment by bigint** [comment]
@Seroxdesign thanks, I fixed the conflicts now 🙏🏻

**Comment by Seroxdesign** [comment]
@bigint Could you go on the QA, connect your wallet and just stay there for a minute or two?  

For me the screen is freezing even after RPC is resolved.

**Review by Seroxdesign — APPROVED** [review]
I have checked all the removed packages and done QA on the link, my requested changes have been made and the RPC connection bug has been dealt with.

Thank you @bigint, good work

**Review by samirsalem — APPROVED** [review]

**Pull request merged**
