### PR TITLE
Create qa.yml

### LINKED ISSUE #361: deploy staging.ricochet.exchange on IPFS + fleek using CI
Workflow proposal:
- Create a new QA branch
- Create a pr against QA branch
- Automate some checks on code (audit  security, eslint checks etc)
- Create a preview env using current ci
- Once pr is merged to QA branch
- We trigger deploy to staging env using fleek
- Once staging env is validated the changes can be deployed in production

### PR DESCRIPTION
**Pull request by geekypandey**
Github Action for quality check and to deploy on IPFS using fleek.

Fixes #361 

**Changes proposed in this pull request:**

- Created the CI as per steps mentioned in the issue.
- The CI will run `eslint` and `npm audit` on the content of the PR, and will comment the results. 
- After merging, the Fleek CI workflow will be triggered to deploy to IPFS, and it will be deployed.

Some setup is required to make this work from the maintainer:

1. Create an account on fleek and add the Hosting API key to Github secrets with name `FLEEK_API_KEY`.
2. Install and build the application (`yarn install && yarn build`)
3. [Install](https://docs.fleek.co/fleek-cli/overview/) fleek cli locally and run `fleek site:init`. You will prompted for team id, which can be found in the url after logging into [fleek](https://fleek.co/).
4. Select `Create New Site` when prompted. 
5. Select `build` directory when prompted to _Choose public directory_. A `.fleek.json` file will be created.
6. Change the site name as required on the website and then accordingly change it in `.fleek.json` and make commit.
8. Now create a qa branch from v2.

Worked on this with @hrishibhattu 💜

### CODE REVIEW

**Comment by geekypandey** [comment]
The working flow as per the issue #361 :

1. A PR is created against the `qa` branch
2. Lint and security audit checks are performed on this PR.
3. If linting fails the CI action will abort.
4. A preview environment is created using current CI. [deployed on aws]
5. After reviewing the PR, it is merged to `qa` branch.
6. On merging, the application on `qa` branch will be deployed on IPFS using fleek.

Please comment if any modifications are required! 😄

**Comment by mikeghen** [comment]
@geekypandey, I see this, looks good, I need a day or two to get this setup, thanks for putting this together

**Comment by geekypandey** [comment]
@mikeghen sure!  👍

**Comment by samirsalem** [comment]
I'll review this before the end of the week, thanks for your help with that

**Comment by mikeghen** [comment]
@geekypandey I spent a good amount in Fleek but I can't find how to get this `FLEEK_API_KEY` out of their platform yet

**Comment by mikeghen** [comment]
Nvm, I found it, tucked away

**Comment by geekypandey** [comment]
I should have mentioned about it😅. my bad. Let us know if you face any other issue.

**Comment by geekypandey** [comment]
@mikeghen any update on this?

**Comment by samirsalem** [comment]
this looks good, sorry if it took some time to review this, a few questions:
how do we get the link of the generated deployment?

**Comment by geekypandey** [comment]
no worries 😄
The link can be found in `.fleek.json` file. It is initially generated randomly and can be modified later.

**Comment by samirsalem** [comment]
the linkk for the qa environment should be putted into a comment in gh actions

**Comment by geekypandey** [comment]
okay, we were thinking since the link would be permanent so we could maybe put that in the description of the repository or maybe in README. What are your thoughts about that?

**Comment by samirsalem** [comment]
I would personally put it in both locations, a comment in actions and in readme

**Comment by geekypandey** [comment]
okay, it shouldn't be too much work to do that. I will test it on my fork and then update the PR.

**Comment by geekypandey** [comment]
@samirsalem We have updated the Github Action to comment the fleek site link in the PR.

**Comment by mikeghen** [comment]
I think I will need help getting this to work with Fleek, I can't even get the app deployed on Fleek @geekypandey, @zhyd1997 was able to get it deployed to fleek though

**Comment by zhyd1997** [comment]
@mikeghen

PR: https://github.com/Ricochet-Exchange/ricochet-frontend/pull/624

**Comment by geekypandey** [comment]
> I think I will need help getting this to work with Fleek, I can't even get the app deployed on Fleek @geekypandey, @zhyd1997 was able to get it deployed to fleek though

sure. Let us know when you are free, we can setup a discord call for this.

**Comment by zhyd1997** [comment]
@geekypandey 

You can see more details here: https://discord.com/channels/862796510604296263/966423687974776972

**Comment by 0xSero** [comment]
Can I have an update on this?

**Comment by geekypandey** [comment]
sorry, I was a little busy for the last two weeks, but I can help on setting it up this week. Can you please reopen this PR?

**Comment by hrishibhattu** [comment]
@Seroxdesign We can help get this set up immediately.

**Comment by 0xSero** [comment]
@geekypandey 

Please keep me updated on the status of this bounty

**Comment by geekypandey** [comment]
sure! I will keep you updated on this.

**Comment by 0xSero** [comment]
Updates please

**Comment by hrishibhattu** [comment]
Available to help set Fleek deployment up with @geekypandey pretty much everyday from 12 noon EST to 3pm EST. @samirsalem 
We've tested it to work fine before submitting the PR.
Let me put more detailed steps here, and if that doesn't help we can set up a call too if you're open to that.

**Comment by hrishibhattu** [comment]
We've made a video to demo the setup process:
https://youtu.be/8dNGwdjMInQ
@Seroxdesign @mikeghen 
If there are any more concerns we're happy to help 😄

**Comment by 0xSero** [comment]
Let's set up a call so I understand better how this works

**Comment by hrishibhattu** [comment]
Sure thing

**Review by mikeghen — APPROVED** [review]

**Comment by mikeghen** [comment]
Sorry it took me so long to review and approve, the video was super helpful

**Comment by mikeghen** [comment]
@geekypandey, I think I still might need your help with this set up

**Comment by geekypandey** [comment]
@mikeghen sure, let me know what time would be suitable, we could take this over discord.

**Pull request merged**
