### PR TITLE
fix: added a toast for when an affilaite tries to stream.

### LINKED ISSUE #600: Create a toast for when an affilaite tries to stream
**Describe the bug**

Affiliates are not allowed to open a stream to the app. Right now, there's no feedback that says this. It's confusing to affiliates when they try to stream they get an error in metamask. This bug is about giving the affiliates a clear message that they can't stream if they try.

**To Reproduce**

1. Register a wallet as an affiliate
2. Fund the wallet with any token
3. Open up a stream

**Expected behavior**

There should be a red message that says "Affiliates can not stream"

**Screenshots**

In the console this is what gets logged when an affiliate tries to stream to the app:
unknown

**Additional context**

Solve this with a message in the toast, those red error messages at the bottom left of the app

### PR DESCRIPTION
**Pull request by zhyd1997**
Fixes #600

### CODE REVIEW

**Comment by zhyd1997** [comment]
need QA to verify before merging...

**Comment by zhyd1997** [comment]
https://user-images.githubusercontent.com/31362988/161336121-bb6dab31-3e09-4aea-9fe7-1a8916fd7c9f.mov

**Review by 0xSero — DISMISSED** [review]
I looked into the code and I see that you have addressed the issue as requested.
I could not test the addition in browser. So I am referring @josealonso to do the QA test.

We could get rid of the nested if statement like this 

if (e.code !== -32603) return
if (e?.data?.message === 'execution reverted: noAffiliates') {
  return 'Affiliates can not stream';
}
    return e.data?.message;
  }

**Comment by zhyd1997** [comment]
@Seroxdesign 

I think the nested `if` statement is necessary.

here is an example, you will see the statement `return 'Operation failed. Refresh the page or try again later.';` will not be handled:

```js
const fakeErrors = [
  { data: { error: 'Invalid address' } },
  { code: 4001, message: 'Invalid signature' },
  { code: -32603, data: { message: 'execution reverted: noAffiliates' } },
  { code: -32603, data: { message: 'execution reverted: test' } },
  { code: -32602, data: { message: 'invalid params' } },
];

// PR change.
const transformError = (e) => {
  if (e?.data?.error) {
    return e.data.error;
  }
  if (e.code === 4001) {
    return e?.message;
  }
  if (e.code === -32603) {
    if (e?.data?.message === 'execution reverted: noAffiliates') {
      return 'Affiliates can not stream';
    }
    return e.data?.message;
  }
  return 'Operation failed. Refresh the page or try again later.';
};

// CR change
const transformErrorRC = (e) => {
  if (e?.data?.error) {
    return e.data.error;
  }
  if (e.code === 4001) {
    return e?.message;
  }
  if (e.code !== -32603) return;

  if (e?.data?.message === 'execution reverted: noAffiliates') {
    return 'Affiliates can not stream';
  }

  return e.data?.message;
  return 'Operation failed. Refresh the page or try again later.';
};

for (let i = 0; i < fakeErrors.length; i++) {
  const err = fakeErrors[i];
  if (transformError(err) !== transformErrorRC(err)) {
    console.log('original error is: ', err);
    console.log('transforError result is: ', transformError(err));
    console.log('RC result is: ', transformErrorRC(err));
    console.log('they are not same');
  } else {
    console.error('OK! transformError and RC are same.');
  }
}

```

**Review by mikeghen — APPROVED** [review]

**Review by mikeghen — CHANGES_REQUESTED** [review]
This isn't working for me when I test with my affiliate address, it still opens a transaction that will revert. See screenshot

Screen Shot 2022-04-21 at 10 10 57 AM

**Comment by zhyd1997** [comment]
@mikeghen got it.

**Review by mikeghen — APPROVED** [review]
nice work @zhyd1997, thank you

**Pull request merged**
