### PR TITLE
Loading Page for Rexvault/bank

### PR DESCRIPTION
**Pull request by Seroxdesign**
Fixes #

**Changes proposed in this pull request:**

- Changed Vault container to fetch data without user visiting bank page 
- Changed Bank and Vault pages to include LoadingPopUp
- Created LoadingPopUp comment

loaidng
asvsdv
sdvsdvsdv

This PR is for the issue: https://github.com/Ricochet-Exchange/ricochet-frontend/issues/339

### CODE REVIEW

**Review by josealonso — CHANGES_REQUESTED** [review]
The popup with the progress bar does its work. Better than waiting with no loading graphics.
However, when you click on Banks, then on another tab and later you come back to the Banks tab, the popup shows up again, although the data are already on the screen. Apart from that, it's an improvement.
I think @sunnyjaycer was thinking about some kind of animation and also his feedback is always better than mine for UX. So I'll just leave this as a comment.

**Review by zhyd1997 — COMMENTED** [review]
Try this solution to solve the popup still appeared when back again:

useState
conditional rendering

A similar logic like `VaultsContainer` did.

Good work!

**Comment by Seroxdesign** [comment]
The changes requested by @josealonso and @zhyd1997 have been implemented, the bank loading animation will only occur on first load

**Comment by josealonso** [comment]
It has been fixed for the Vault tab, but not for the Bank tab.

**Comment by Seroxdesign** [comment]
> Try this solution to solve the popup still appeared when back again:
> 
> useState
> 
> conditional rendering
> 
> A similar logic like `VaultsContainer` did.
> 
> Good work!

image

**Comment by Seroxdesign** [comment]
Requested changes have been made in both bank and vault pages. Should be good now @zhyd1997

**Review by zhyd1997 — APPROVED** [review]

**Review by abhisheknaiidu — APPROVED** [review]
LGTM, awesome work @Seroxdesign 🚀

**Pull request merged**
