### PR TITLE
Successfully Ran Ricochet DApp Locally 

### PR DESCRIPTION
**Pull request by 0xkenichi**
Fixes #

**Changes proposed in this pull request:**

-
-
-

### CODE REVIEW

**Comment by 0xSero** [comment]
@finch-theworst can you put a video of you running the dapp locally so I can verify?

**Comment by 0xSero** [comment]
@finch-theworst are you still working on this?

**Comment by 0xkenichi** [comment]
> @finch-theworst are you still working on this?
> 

Oh my bad, the video right?

**Comment by 0xSero** [comment]
> > @finch-theworst are you still working on this?
> 
> Oh my bad, the video right?

yes, just to confirm u got it running

**Pull request closed without merging**
