### PR TITLE
Vault page feedback

### PR DESCRIPTION
**Pull request by Seroxdesign**

### CODE REVIEW

**Comment by josealonso** [comment]
My review:

1.- The Vault button can now be seen, but that page only contains a button that takes you to the Bank tab. What is the purpose of the "Vault" tab, then ? Anyway, this has been SOLVED.

2.- The Vault button does not appear under the “Tutorial” button. SOLVED.

3.- withdraw / deposit and borrow / repay buttons not aligned to the same right side position. Not aligned in Firefox for desktop.

4.- Collaterallization and liquidation price titles have unnecessary large spacing in-between the numbers and the title. SOLVED.

5.- Users can input negative numbers and into the withdraw/deposit/borrow/repay fields and the button “enabled”. Resolved as long as you don't type the values. This can be improved, I think.

6.- All button texts are lowercase. The "Max" and "Cancel" buttons are not lowercase.

7.- Repay button always opens with “give allowance” button: SOLVED.

8.- Sign in with web3 button is white on white. I couldn't check it since I culdn't disconnect my wallet.

9.- Transaction error kind of breaks the UI in vaults page: Solved, but this message is confusing: "Metamask transactions take time to verify, please return at a later time." SOLVED.

10.- Repay max button can be used, it allows user to click on repay button even if the user has not given allowance. SOLVED

11.- Infinite loading spinner is shown to the user and the vault buttons are disabled even after the borrowing transaction has been confirmed. Very clear message: "This transaction is being processed, check your Metamask wallet extension and please do NOT leave or refresh this page until confirmation is complete.", but it takes a while for the Infinite loading spinner to stop after the tx has been approved. Although this probably can't be avoided. SOLVED

**Comment by josealonso** [comment]
@Seroxdesign, I had to open it again. Let's try not to do this again, because creating a PR consumes resources and we want to avoid that. @samirsalem is the CI guy.

**Comment by Seroxdesign** [comment]
Okay will improve on it, thank you

**Review by josealonso — COMMENTED** [review]
I left my review as a comment.

**Pull request closed without merging**
