### PR TITLE
chore: fix stream issue for larger streams

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
**context:** when opening 100,000 RIC per month stream. It did not work, but when changed the number to 100,005 RIC per month it worked. 

ref - https://app.dework.xyz/ricochet-exchange-da/main-space-32902?taskId=4177b7b6-5d83-49d7-a8bb-481e91f449d7

**solution:** Math.floor was not that calculating that precisely so using big.js for all the mathematical calculations, it seems to be working fine now

Screenshot_2023-02-20_at_2 42 12_AM

### CODE REVIEW

**Comment by 0xSero** [comment]
x;, vd

Transaction is populating with [object object] and transaction is failing tried to open a stream of 100k RIC > USDC

**Review by mikeghen — APPROVED** [review]
LGTM

**Comment by mikeghen** [comment]
@Seroxdesign I'll leave the squash and merge to you

**Comment by 0xSero** [comment]
> @Seroxdesign I'll leave the squash and merge to you @abhisheknaiidu you're passing a wrong value to startFlow

```
Error: [object Object]
    e ethereum.ts:298
    Babel 5
        d
        _invoke
        x
        r
        s
[startFlow.ts:32:10](https://ricochet-frontend-afozekt2o-seroxdesign.vercel.app/static/js/store/main/sagas/startFlow.ts)
```

This is not working properly

**Pull request merged**
