### PR TITLE
Disable upgrade button if not approved - fix #527

### LINKED ISSUE #527: Upgrade button needs to be disabled if not approved
The upgrade button isn't disabled if no approval is done, the result is a reverting transaction opening in metamask if you just click upgrade:
Screen Shot 2022-02-28 at 4 39 59 PM

### PR DESCRIPTION
**Pull request by spitko**
[Commit that introduced bug](https://github.com/Ricochet-Exchange/ricochet-frontend/commit/230909b07f698849bb1aabc9ad22f24200da8a28#diff-57c8296ae9941a36578a5ca265cdd56ead41101d0425c05ed4b554b71dd4a3b1L42) 

Note that upgrade button is currently not automatically enabled after approval and a refresh is required.

### CODE REVIEW

**Comment by mikeghen** [comment]
Thank you @spitko!

**Review by zhyd1997 — COMMENTED** [review]
Maybe check if `approved` in redux store is true or call superfluid API to obtain `allowance` to make sure that no refreshing is required

**Comment by spitko** [comment]
> Maybe check if `approved` in redux store is true or call superfluid API to obtain `allowance` to make sure that no refreshing is required

There is already a [check](https://github.com/Ricochet-Exchange/ricochet-frontend/blob/6d5341849154bd9a50fc1acc2bf0b93e989ee625/src/store/main/sagas/approveSaga.ts#L58) done after the approval, but it returns false.

imo this is a separate issue

**Comment by zhyd1997** [comment]
@spitko 
I am not familiar with the code related, follow your style.

**Review by mikeghen — APPROVED** [review]

**Comment by mikeghen** [comment]
Thank you @spitko !

**Pull request merged**
