### PR TITLE
Fix affiliate ID

### PR DESCRIPTION
**Pull request by seemwavy**
Fixes #

**Changes proposed in this pull request:**

surfwavy/dw-110/fix-referral-link-displa

### CODE REVIEW

**Review by mikeghen — APPROVED** [review]
@Seroxdesign, I'll leave this for you to merge as you see fit. I worked with @seemwavy on this today.

**Comment by 0xSero** [comment]
One last note:

In the future when you want to work on a bounty, after pulling latest changes. Please create a new branch with the following command in git:

git checkout -b name-of-branch-here

Name it something clear, in this example it would be:

bug/fix-affiliate-id

This will help us keep track of different PRs, in case we have any issues later on @seemwavy

**Comment by seemwavy** [comment]
> One last note:
> 
> In the future when you want to work on a bounty, after pulling latest changes. Please create a new branch with the following command in git:
> 
> git checkout -b name-of-branch-here
> 
> Name it something clear, in this example it would be:
> 
> bug/fix-affiliate-id
> 
> This will help us keep track of different PRs, in case we have any issues later on @seemwavy

Understood. Shall I resubmit the branch with these changes?

**Comment by mikeghen** [comment]
> Understood. Shall I resubmit the branch with these changes?
@seemwavy You can:
```
git checkout -b  bug/fix-affiliate-id
``` 
on the v2 branch of your repo. After the checkout, I think you then run:
```
git push --set-upstream origin bug/fix-affiliate-id
```

**Comment by seemwavy** [comment]
> > Understood. Shall I resubmit the branch with these changes?
> > @seemwavy You can:
> 
> ```
> git checkout -b  bug/fix-affiliate-id
> ```
> 
> on the v2 branch of your repo. After the checkout, I think you then run:
> 
> ```
> git push --set-upstream origin bug/fix-affiliate-id
> ```

The changes have been made to the branch

**Comment by mikeghen** [comment]
Closed in favor of #863

**Pull request closed without merging**
