### PR TITLE
feat: added received so far.

### LINKED ISSUE #598: Show "amount received so far" below "amount streamed so far"
As a customer, I want to see how much I streamed in so far relative to how much I received.

Right now I do this by checking both the streams page and the distributions page. It would help to have these both on the same page.

Screen Shot 2022-03-21 at 10 49 51 AM

### PR DESCRIPTION
**Pull request by zhyd1997**
Resolves #598

### CODE REVIEW

**Comment by 0xSero** [comment]
I do not have the stream limitation @josealonso  I believe this is an issue you've had can you confirm

**Comment by 0xSero** [comment]
No received so far on the frontend.

Can you confirm this?

**Comment by zhyd1997** [comment]
@Seroxdesign 

Yes, because we can not stream on market.

**Comment by 0xSero** [comment]
I had streams open yet no received so far was available to me

**Comment by 0xSero** [comment]
I had streams open yet no received so far was available to me

**Comment by zhyd1997** [comment]
> I had streams open yet no received so far was available to me

It will be displayed as 'Streamed ... so for'.

I think if we can send stream like superfluid but also contain market info payload, it will be displayed finally.

**Review by 0xSero — APPROVED** [review]
Looks good to me

**Pull request merged**
