### PR TITLE
[WIP] #145 Referral System Front End

### PR DESCRIPTION
**Pull request by abstractpoint**

### CODE REVIEW

**Comment by mikeghen** [comment]
@abstractpoint, do you have some images you could put here?

**Comment by mikeghen** [comment]
It makes me sleep better at night knowing you already worked out this feature on the frontend and @shreyaspapi got it on the backend

**Comment by abstractpoint** [comment]
Sure thing. This feature is a big deal, can't wait see it in the wild being used soon.
Screenshot 2021-12-22 at 15 40 54
#145-ref

**Comment by mikeghen** [comment]
@abstractpoint thanks for queuing this up, This will probably remain open until version 2.0 contracts are ready, I believe that the first contracts we can test with will be another week or two.

**Comment by shreyaspapi** [comment]
@abstractpoint Referral contract has been deployed, `ABI` for the contract is changed. Mainly the naming `user -> customer`.

**Comment by bigint** [comment]
Is this PR still active, it has lot of conflicts better rebasing or reopen a ew PR 🙇🏻

**Pull request closed without merging**
