### PR TITLE
Feat/interactive stream manager

### LINKED ISSUE #97: Interactive Stream Manager
- Show users a visualization of their streams and allow them to create, edit, delete flows from the visualization
- The idea is to have inputs and outputs, the lines connecting them are the flow rates and they can be edited 
2527f45c-758f-4f8b-9cc6-d56ba4d7fe1a

### PR DESCRIPTION
**Pull request by zhyd1997**
Resolves #97

### CODE REVIEW

**Review by mikeghen — CHANGES_REQUESTED** [review]
I think the buy sell language in the pop up is backwards
Screen Shot 2022-05-26 at 8 57 35 AM

**Review by mikeghen — CHANGES_REQUESTED** [review]
RIC>>USDC fails with error:
```
"execution reverted: CFA: flow does not exist"
```
Screen Shot 2022-05-26 at 9 04 50 AM

**Comment by mikeghen** [comment]
> RIC>>USDC fails with error:
> 
> ```
> "execution reverted: CFA: flow does not exist"
> ```


looks like this is an issue opening to the 2nd side, so for a USDC<>ETH market, going USDC>>ETH works, ETH>>USDC fails

**Review by mikeghen — CHANGES_REQUESTED** [review]
Can you make sure you add the tool tips from the Markets page? And in general can you make this style look more like what's on the markets page?

Screen Shot 2022-05-26 at 9 08 13 AM
Screen Shot 2022-05-26 at 9 08 43 AM

**Review by mikeghen — CHANGES_REQUESTED** [review]
Can you remove "Please make sure all the information here is correct!" this warning is a bit unnecessary and it gets covered up but the tool tip anyway

**Comment by mikeghen** [comment]
> I think the buy sell language in the pop up is backwards 

Fixed, thanks

**Review by mikeghen — CHANGES_REQUESTED** [review]
Can you add units to these values? 
Screen Shot 2022-05-26 at 2 05 32 PM

**Comment by zhyd1997** [comment]
@mikeghen Done

Screen Shot 2022-05-27 at 07 33 28
Screen Shot 2022-05-27 at 07 33 46
Screen Shot 2022-05-27 at 07 34 48

**Review by mikeghen — APPROVED** [review]
Screen Shot 2022-05-27 at 9 31 46 AM

**Pull request merged**
