### PR TITLE
feat: trade history.

### LINKED ISSUE #692: Trade History Page
As a trader, its difficult to figure out how much was streamed in and how much was received back through distriubtions. This issue is a make a "Trade History" page that show the following information in a table view:
1. Stream start date, with link to start stream txn
2. Stream end date, with link to close stream txn
3. Input amount, native token amount
4. Input amount, USD amount (at time of stream close)
5. Output amount, native token amount
6. Output amount, USD amount (at time of stream close)
7. Profit or loss: `(USD amount out - USD amount in) / USD amount in = Pnl`

Each trade should be a start and end stream, call that a trade. If a user is using a market and starts and ends streams many times, each start-end stream should be a trade. For example:
1. Start streaming USDC>>ETH
2. Stream 100 USDC for 0.1 ETH
3. Stop stream, record as 1 trade 100 USDC to 0.1 ETH
4. Start streaming USDC>>ETH again
5. stream 100 USDC to 0.11 ETH
6. Stop stream, record as 1 trade 100 USDC to 0.11 ETH

Here is a mock up what I had in mind:
IMG_5167

### PR DESCRIPTION
**Pull request by zhyd1997**
Resolves: #692 

**limitation**:

* only show streams that have been `terminated` because the superfluid subgraph only stores the latest state of distribution.

### CODE REVIEW

**Comment by zhyd1997** [comment]
current UI with mock data:

dashboard

I will add the information that what the dashboard is (record the stopped stream and the active stream is in the interactive stream manager tab).

**Comment by zhyd1997** [comment]
**Update:** <del>update a stream should be treated as stopping the current stream and starting a new stream.</del> (see below comment for details).

**Comment by zhyd1997** [comment]
`Input` field criteria：

- `sender` should be the user account.
- `receiver` should be in the range of all of the market`exchangeAddress`.
- `updatedAtTimestamp` should be not equal to `createdAtTimestamp`.
   (if so, it's an active stream and should not be including in trades history).
- `currentFlowRate` should be '0' or it's hard to decide if the user updated it or stopped it and if the record update event, it will disappear if the user stops it, which is confusing for the user.

create
update
delete

**Comment by zhyd1997** [comment]
`Output` field criteria:

- `subscriber` should be the user account.
- distribution `updatedAtTimestamp` should be equal to `stream`'s `updatedAtTimestamp`.
- `indexId` should not be `subsidyIndex` or should be `outputIndex`.

**Comment by mikeghen** [comment]
Nice work on this @zhyd1997, I see some info when I visit this good work, looks right too for my ETH>>USDC stream

The polygonscan links don't seem to work for the start or end date yet

I have this transaction that I think is USDC>>RIC but shows up USDC >> ETH with 0 ETH so maybe you're looking at the subsidy for RIC<>USDC since that's set to ETH

Screen Shot 2022-06-05 at 5 55 13 PM

**Comment by zhyd1997** [comment]
> Nice work on this @zhyd1997, I see some info when I visit this good work, looks right too for my ETH>>USDC stream
> 
> The polygonscan links don't seem to work for the start or end date yet
> 
> I have this transaction that I think is USDC>>RIC but shows up USDC >> ETH with 0 ETH so maybe you're looking at the subsidy for RIC<>USDC since that's set to ETH
> 
> Screen Shot 2022-06-05 at 5 55 13 PM

Yes, I need use query `FlowUpdateEvents` to get more streams and transactionHash, instead of query `streams` directly.

The subsidy should be excluded, I will figure it out later, and I have asked a question on superfluid discord, waiting for their response.

**Review by mikeghen — CHANGES_REQUESTED** [review]
I see only 7 records on the page but it says 1-10
Screen Shot 2022-06-10 at 9 08 17 AM

Also, my test wallet address is this: 0xdcf718e5B3407BB50a3094BbfD6CC50D2b491649

I have some trades in the trades table that Im not sure are correct, maybe you could query for this address as a test and see what's going on with it, the trades shown in the UI are:
Screen Shot 2022-06-10 at 9 10 10 AM

Screen Shot 2022-06-10 at 9 10 16 AM

**Comment by zhyd1997** [comment]
@mikeghen 

the wired page is caused by some edge cases, which `ETH` should be mapped as `WETH`, `MATIC` should be mapped as `WMATIC` in `marketPrices` state https://github.com/Ricochet-Exchange/ricochet-frontend/pull/694/commits/e6e781f3e3ae690f43c2ee84f204350dbde47c12.

**Review by mikeghen — CHANGES_REQUESTED** [review]
could you take the information from within the `()` and make them their own columns? Can you add three more columns for the 3 values I squared?
Screen Shot 2022-06-20 at 7 01 38 PM

**Review by mikeghen — APPROVED** [review]

**Pull request merged**
