### PR TITLE
Move max button inside Amount Input text box issue#70

### PR DESCRIPTION
**Pull request by qasimmehdi**
Solved #70 . I have moved the max button inside amount input. I also followed the development pattern used in this repo properly.

### CODE REVIEW

**Comment by qasimmehdi** [comment]
Screenshot 2021-11-07 at 5 22 48 AM

**Comment by abstractpoint** [comment]
Thank you for this Qasim. I'm seeing a problem with the button on smaller screens. See screenshot. Might be also worth styling is as just blue text (so no background and rounded corners, and right-align inside textbox)

**Comment by abstractpoint** [comment]
Screenshot 2021-11-07 at 11 15 16

**Comment by qasimmehdi** [comment]
Fixed button size issue and changed color back to primary. Also I removed the max wrap border on smaller devices, is that alright?
Screenshot 2021-11-07 at 5 06 07 PM

**Comment by mikeghen** [comment]
Excellent work @qasimmehdi, I just tested this on staging.ricochet.exchange, it will be live on app.ricochet soon 👏 🚰

**Pull request merged**
