### PR TITLE
Ft/market filter

### PR DESCRIPTION
**Pull request by mindsgn**
Fixes #

**Changes proposed in this pull request:**

- add filter buttons 
- Buy: should filter down to all the USDC/DAI/ibAlluoUSD>>X markets
- Sell: This should filter down to all the MATIC/ETH/BTC/ibAlluoETH/BTC>>Xmarkets
- Yield: This should filter to just the ibAlluo markets

### CODE REVIEW

**Comment by mikeghen** [comment]
Thanks for working on this @mindsgn

**Comment by 0xSero** [comment]
acw#

@mindsgn, good job it works 

Can we make the filter options a dropdown?
It's more consistent with our design~

These colors are a bit harsh:

image

**Comment by 0xSero** [comment]
@mindsgn are you still working on this?

**Comment by 0xSero** [comment]
@mindsgn if this is not being updated I will need to close it out

**Comment by mikeghen** [comment]
> acw#
> 
> @mindsgn, good job it works
> 
> Can we make the filter options a dropdown? It's more consistent with our design~
> 
> These colors are a bit harsh:
> 
> image

@Seroxdesign if it's a drop down and not 3 buttons people might not even see it, I agree colors are hard, can they just be made ricochet blue?

**Comment by mindsgn** [comment]
I have made the drop-down already.

> > acw#
> > @mindsgn, good job it works
> > Can we make the filter options a dropdown? It's more consistent with our design~
> > These colors are a bit harsh:
> > image
> 
> @Seroxdesign if it's a drop down and not 3 buttons people might not even see it, I agree colors are hard, can they just be made ricochet blue?

**Comment by 0xSero** [comment]
I think the dropdown is clear @mikeghen, it's standard to use dropdowns for filters, adding buttons in there would fill out the UI IMO

**Review by 0xSero — APPROVED** [review]
Read through this and seems fine, thanks @mindsgn

**Pull request merged**
