### PR TITLE
Uniwhales waterdrop

### PR DESCRIPTION
**Pull request by 0xSero**
Fixes #

**Changes proposed in this pull request:**

- add uniwhales waterdrop
- realign page components
- clean up

### CODE REVIEW

**Review by mikeghen — CHANGES_REQUESTED** [review]
I tried to use a wallet that is eligible, but it says I am ineligible, I check on the contract to see that I was added to the contract correctly, it is added right, so this seems like something on the frontend
Screen Shot 2023-01-13 at 10 58 12 PM
Screen Shot 2023-01-13 at 10 58 00 PM

**Review by mikeghen — CHANGES_REQUESTED** [review]
Another review is to make the W in Uniwhales capitalized. I also think the logo would look better on a white circular background

**Comment by 0xSero** [comment]
This PR also addresses this issue:

https://app.dework.xyz/ricochet-exchange-da/clean-up-frontend-an?taskId=6f5211a2-6a8e-41f8-90d1-fa93c0a6dd09

**Review by mikeghen — CHANGES_REQUESTED** [review]
After claiming this, it shows as claimed but does not show me how much has been claimed so far. 

Screen Shot 2023-01-16 at 2 15 28 PM

**Comment by 0xSero** [comment]
> After claiming this, it shows as claimed but does not show me how much has been claimed so far.
> 
> Screen Shot 2023-01-16 at 2 15 28 PM

Resolved
image

**Review by mikeghen — CHANGES_REQUESTED** [review]
This wallet is ineligible for the claim for Alluo but shows its claimed 1000 RIC:
Screen Shot 2023-01-17 at 2 13 55 PM
This wallet did do the claim for UWL and thats working great :+1:

**Review by mikeghen — APPROVED** [review]
Looks good to me, follow up PR will animate the numbers

**Pull request merged**
