### PR TITLE
fix: UI issues

### LINKED ISSUE #442: UI Issues, features and refactors
- [x] Invert the price red to down and green to up ($100)

Screenshot 2022-02-19 at 3 55 54 PM

- [x] Improve coin image size in wallet page ($50)

Screenshot 2022-02-19 at 4 02 11 PM

- [x] Add trend arrow to netflow like in superfluid ($100)

Screenshot 2022-02-19 at 4 13 02 PM

### PR DESCRIPTION
**Pull request by bigint**
Fixes #442

Screenshot 2022-02-19 at 4 20 25 PM
Screenshot 2022-02-19 at 4 20 39 PM
Screenshot 2022-02-19 at 4 20 47 PM

### CODE REVIEW

**Comment by bigint** [comment]
cc @abhisheknaiidu

**Review by abhisheknaiidu — APPROVED** [review]

**Comment by shreyaspapi** [comment]
> * https://a380c3be5e6284f4ca1dfc37a12b3033-851332533.eu-west-1.elb.amazonaws.com/fix-442  **Markdown** ✨

I can't access the test environment. Am I missing something?

**Review by josealonso — APPROVED** [review]

**Comment by josealonso** [comment]
Approved, but can't be merged, @bigint

**Comment by bigint** [comment]
Conflicts are huge, opening a new PR and closing this 🙏🏻

**Pull request closed without merging**
