### PR TITLE
Fixing max buttons in vault transactions

### PR DESCRIPTION
**Pull request by 0xSero**
Fixes #

**Changes proposed in this pull request:**
 
- Created maxAvailableDepositRIC/USDC function to place correct value in input on max deposit
- Created maxAvailableBorrow function to place correct value in input on max Borrow
- Created MaxAvailableWithdraw

### CODE REVIEW

**Review by mikeghen — CHANGES_REQUESTED** [review]
First I think theres some merge conflicts so fix those.

Second, there's a design issue in the contract and the max borrow is actually 155% not 150%, so you see if you click max then borrow, the txn in Metamask will revert. Could you change it so the max used is 155%, or 5% + collateralizationRatio. The small 5% buffer is needed due to how interest rates are calculated.

**Comment by Yuxanju** [comment]
You will have to synchronize your wallet and debug it

**Comment by 0xSero** [comment]
Resolved conflicts still need to add the 5%

**Comment by 0xSero** [comment]
Requested change has been implemented, awaiting review and merge @mikeghen

**Review by mikeghen — CHANGES_REQUESTED** [review]
@Seroxdesign can you double check this works right, because now its letting me max borrow at a 148% collateralization ratio which definitely fails
Screen Shot 2022-03-07 at 11 51 51 AM

**Review by mikeghen — APPROVED** [review]
LGTM :+1: thanks @Seroxdesign

**Pull request merged**
