### PR TITLE
Implementing P2P streaming using superfluid core sdk 

### PR DESCRIPTION
**Pull request by 0xSero**

### CODE REVIEW

**Comment by 0xSero** [comment]
Do not merge, work in progress

**Comment by 0xSero** [comment]
image

Added the moneyStreaming functions from the superfluid SDK, if you click the button on top that says send a modal will open:

image

The user can input an address, flow amount and choose a token to start a stream to the recipient
User can also click the recent stream button to open a window of all recent streams to allow user to delete or modify the streams.

image

**Review by josealonso — COMMENTED** [review]
I received his money, but I couldn't sent any money to him. Rather, my transaction didn't go through, but it didn't fail, either. Still waiting. 
That feature has a lot of work. Not only he did the frontend task, but he also implemented a batch-call using the SF sdk-core.

The UI needs some improvements
-  The "Activity History" window can't be closed.
- Adding some hints and messages for the user would be convenient.

The most important part seems to be working, although I don't know why I can't stream money to other user. It might have to do with the blockchain being congested, but it has to be tested by others.

**Comment by 0xSero** [comment]
> I received his money, but I couldn't sent any money to him. Rather, my transaction didn't go through, but it didn't fail, either. Still waiting. That feature has a lot of work. Not only he did the frontend task, but he also implemented a batch-call using the SF sdk-core.
> 
> The UI needs some improvements
> 
>     * The "Activity History" window can't be closed.
> 
>     * Adding some hints and messages for the user are would be convenient.
> 
> 
> The most important part seems to be working, although I don't know why I can't stream money to other user. It might have to do with the blockchain being congested, but it has to be tested by others.

I added a back button so the user can return after checking activity, added some toasts to guide user and improved layout and style, added more space and increased input field size

**Comment by 0xSero** [comment]
@mikeghen could you review this

**Review by mikeghen — CHANGES_REQUESTED** [review]
1. If we do this feature, there must be a place to see open streams, the activity page isn't the place to see it
2. I think the styling has too much white space, the box on the SF dashboard is much smaller, so lets make it look more like theirs, less whitespace. 
3. When I send the page shows this below, the txn still confirms a stream opens just fine. But this is confusing to me since it says "no results found"
Screen Shot 2022-03-23 at 10 18 54 AM

**Comment by 0xSero** [comment]
@mikeghen 
This has been finalised, reviewed and tested.

**Review by mikeghen — CHANGES_REQUESTED** [review]
@Sero#0676, I'll put some review on it, right away I see that box at the bottom `Outgoing Streams (0) ` That should be moved to the Streams page since it doesn't belong on the Markets page.

Also, merge the latest changes from the v2 branch into this branch

**Comment by 0xSero** [comment]
Moved stream manager to invest/streams:

image

Removed stream manager from all other invest/routes:

image

Removed console.logs

**Review by mikeghen — CHANGES_REQUESTED** [review]
1. Fix the type here so it doesn't look so messy, maybe just bold text instead of italics
Screen Shot 2022-04-21 at 11 42 30 AM

2. Can you use the existing toast styling this rainbox stuff is a discontinuous look from the rest of the UI?
Screen Shot 2022-04-21 at 11 44 21 AM

3. Unfortunately, the stream I opened in app.ricochet doesn't appear undert the "Streams" page for me, I confirmed on app.superfluid the stream was infact opened and is streaming, so its just not the case it shows up in app.ricochet. I also waited a few minutes and refreshed the app.ricochet a few times, nothing showed up, maybe try again with a new wallet that doesn't have any existing streams and make sure a stream shows up correctly.
Screen Shot 2022-04-21 at 11 46 28 AM

**Comment by mikeghen** [comment]
I'll be taking the QA bounty for this issue

**Comment by 0xSero** [comment]
> 1. Fix the type here so it doesn't look so messy, maybe just bold text instead of italics
> 
> 
> Screen Shot 2022-04-21 at 11 42 30 AM
> 
>     2. Can you use the existing toast styling this rainbox stuff is a discontinuous look from the rest of the UI?
> 
> 
> Screen Shot 2022-04-21 at 11 44 21 AM
> 
>     3. Unfortunately, the stream I opened in app.ricochet doesn't appear undert the "Streams" page for me, I confirmed on app.superfluid the stream was infact opened and is streaming, so its just not the case it shows up in app.ricochet. I also waited a few minutes and refreshed the app.ricochet a few times, nothing showed up, maybe try again with a new wallet that doesn't have any existing streams and make sure a stream shows up correctly.
> 
> 
> Screen Shot 2022-04-21 at 11 46 28 AM

Form label text fixed:

image

Toasts:

image

Stream manager not showing up:

This was due to QA and Local route links are formatted a little bit differently, mainly the QA links have an additional /pr_name_here appended:

image

**Review by mikeghen — COMMENTED** [review]
I think this UI is a little clunky, can these outgoing streams be displayed as a table like the rest of the streams on this page?
Screen_Shot_2022-04-21_at_5 34 37_PM

**Comment by 0xSero** [comment]
> I think this UI is a little clunky, can these outgoing streams be displayed as a table like the rest of the streams on this page? Screen_Shot_2022-04-21_at_5 34 37_PM

Requested changes have been made, I set it up to be a grid that spans the whole page. decreased modal size and used Ricochet's colors from the console.

image

**Review by mikeghen — CHANGES_REQUESTED** [review]
somethings off with the numbers, I opened streams for 98 USDC to a REX Market (0xf415) but the outgoing stream section shows it as 131$

Screen_Shot_2022-04-22_at_9 29 05_AM


Also that second outgoing stream 0xcd3b is for 100 USDC per month but it shows up as 133$
so somethings not being calculated correctly in the outgoing streams section

**Comment by 0xSero** [comment]
> somethings off with the numbers, I opened streams for 98 USDC to a REX Market (0xf415) but the outgoing stream section shows it as 131$
> 
> Screen_Shot_2022-04-22_at_9 29 05_AM
> 
> Also that second outgoing stream 0xcd3b is for 100 USDC per month but it shows up as 133$ so somethings not being calculated correctly in the outgoing streams section

I made it so outgoing streams to RexMarkets do not appear in the stream manager, that will prevent confusion.

In terms of removing the % buffer:
image
image

**Review by mikeghen — APPROVED** [review]

**Pull request merged**
