### PR TITLE
Fix NaN - To Merge

### PR DESCRIPTION
**Pull request by 0xSero**
Fixes #

**Changes proposed in this pull request:**

- setTimeout in catch block
- test
- console log errors

### CODE REVIEW

**Review by mikeghen — CHANGES_REQUESTED** [review]
@Seroxdesign I can't open up a stream to the USDC<>RIC market, USDC<>MATIC works fine, the error I get is:
```
"Populate Transaction Error - There was an error populating the transaction: {
  "reason": "cannot estimate gas; transaction may fail or may require manual gas limit",
  "code": "UNPREDICTABLE_GAS_LIMIT",
  "error": {
    "reason": "execution reverted: SF: need more gas",
```
I think something about how the gaslimit is computed might be broken in the application.

**Comment by 0xSero** [comment]
> @Seroxdesign I can't open up a stream to the USDC<>RIC market, USDC<>MATIC works fine, the error I get is:
> 
> ```
> "Populate Transaction Error - There was an error populating the transaction: {
>   "reason": "cannot estimate gas; transaction may fail or may require manual gas limit",
>   "code": "UNPREDICTABLE_GAS_LIMIT",
>   "error": {
>     "reason": "execution reverted: SF: need more gas",
> ```
> 
> I think something about how the gaslimit is computed might be broken in the application.

This is unrelated to current task, let's log this issue in dework

**Review by mikeghen — CHANGES_REQUESTED** [review]
No doubt, pulling this amount of data from coingecko is a source of delay since moving data over the network creates latency proportional to the amount of data transmitted. Can you find where ever you're pulling all this and not pull all of this data? You should only need the price AFAIK
Screen Shot 2023-02-04 at 10 48 11 AM

**Review by mikeghen — DISMISSED** [review]
I can't open streams and I get a few different errors trying to do so, Im not exactly sure why:
Screen Shot 2023-02-04 at 10 56 09 AM

**Comment by 0xSero** [comment]
> No doubt, pulling this amount of data from coingecko is a source of delay since moving data over the network creates latency proportional to the amount of data transmitted. Can you find where ever you're pulling all this and not pull all of this data? You should only need the price AFAIK Screen Shot 2023-02-04 at 10 48 11 AM

I looked into the coingecko API and there is no way to filter the data request, we are filtering out the data we need and only storing that so effect on performance should be minimal

**Comment by 0xSero** [comment]
> I can't open streams and I get a few different errors trying to do so, Im not exactly sure why: Screen Shot 2023-02-04 at 10 56 09 AM

This problem  is out of scope, Nite and I tested and we both get conflicting results:

1. Me: I can't start a USDC > RIC stream on https://ricochet-exchange.eth.limo
2. Nite can start a stream on the same PR deployment

------

Issues that could be causing this:

1. having a lot of streams open
2. oracle problems

etc..

I'd recommend making a new issue on dework, I will take care of it early next week.

**Review by nitegeist — APPROVED** [review]
These changes have been tested in staging and fix the issue laid out in the scope. Approved.

**Pull request merged**
