### PR TITLE
Updates the app to support for internationalization

### LINKED ISSUE #425: Make the app ready for internationalization

### PR DESCRIPTION
**Pull request by ramprakashram**
Fixes #425

**Changes proposed in this pull request:**

- Adds english language strings for i18n support
- Updates existing strings to be linked to i18n

### CODE REVIEW

**Comment by josealonso** [comment]
So the *i18n* strings file was almost empty. So bad, most of the developers didn't use internationalization at all. I'm going to increase the bounty value, @ramprakashram, you went through a lot of files. Keep up the good work !!

**Review by josealonso — APPROVED** [review]
I really like sushi user interface with so many languages: Chines, Spanish, Italian, etc.). They even change the button label (*deposit*, *withdraw* and so on) depending on the chosen language.  After going through our code, I think this is not an easy change. 
Therefore, I'm going to approve and merge this changes.

**Comment by ramprakashram** [comment]
Thanks @josealonso.
Looks like we do not have a language switcher in our v2 app yet, maybe we need to create a new issue for it and work on it.

**Comment by josealonso** [comment]
> Thanks @josealonso. Looks like we do not have a language switcher in our v2 app yet, maybe we need to create a new issue for it and work on it.

I suggest you comment that on our discord. You can even open a thread for that feature. It's not a priority now, but maybe it's a good moment, since the UX is being arranged. I don't usually do frontend development myself, I prefer the backend.

**Pull request merged**
